name: libogc2 build

on: [push, pull_request]

jobs:
  build:
    name: Build libogc2
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout libogc2
      uses: actions/checkout@main
      with:
        path: libogc2

    - name: Checkout libfat
      uses: actions/checkout@main
      with:
        repository: extremscorner/libfat
        path: libfat

    - name: Checkout libntfs
      uses: actions/checkout@main
      with:
        repository: extremscorner/libntfs
        path: libntfs

    - name: Build libogc2
      run: make install
      working-directory: libogc2

    - name: Build libfat
      run: make ogc-install
      working-directory: libfat

    - name: Build libntfs
      run: make install
      working-directory: libntfs

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: libogc2
        path: /opt/devkitpro/libogc2

    - name: Checkout gamecube-examples
      uses: actions/checkout@main
      with:
        repository: extremscorner/gamecube-examples
        path: gamecube-examples

    - name: Checkout wii-examples
      uses: actions/checkout@main
      with:
        repository: extremscorner/wii-examples
        path: wii-examples

    - name: Build gamecube-examples
      run: make
      working-directory: gamecube-examples

    - name: Build wii-examples
      run: make
      working-directory: wii-examples

    - name: Upload gamecube-examples
      uses: actions/upload-artifact@main
      with:
        name: gamecube-examples
        path: gamecube-examples/bin

    - name: Upload wii-examples
      uses: actions/upload-artifact@main
      with:
        name: wii-examples
        path: wii-examples/bin
